#ifndef _REDINK_BOARD_LAYOUT_H
#define _REDINK_BOARD_LAYOUT_H 1

#define WIFI_CS_PIN    A2
#define WIFI_RESET_PIN A4
#define WIFI_BUSY_PIN  A3
#define WIFI_GPIO_PIN  -1

#define DISPLAY_CS_PIN      7
#define DISPLAY_DC_PIN      9
#define DISPLAY_SRAM_CS_PIN 10
#define DISPLAY_RESET_PIN   11
#define DISPLAY_BUSY_PIN    12

#define DOTSTAR_DATA_PIN  8
#define DOTSTAR_CLOCK_PIN 6

#endif
