#ifndef _REDINK_BOARD_LAYOUT_H
#define _REDINK_BOARD_LAYOUT_H 1

#define DISPLAY_CS_PIN      21
#define DISPLAY_DC_PIN      14
#define DISPLAY_SRAM_CS_PIN 10
#define DISPLAY_RESET_PIN   33
#define DISPLAY_BUSY_PIN    32

#define LED_BUSY_PIN 2

#endif
